### ISSUE TITLE
Adjust filtering parameters

### ISSUE THREAD

**Issue by bschilder** [neurogenomics/RareDiseasePrioritisation#17]
Following the discussion with @NathanSkene and @KittyMurphy I will adjust the following target filtering criterion accordingly:

1. [x] Experiment filtering based on the ontology level of each phenotype.
2. [x] Remove phenotypes without any age of onset information (ie NA).
3. [x] Filter age of onset using new column "Onset_latest" instead of "Onset_earliest" (which is currently being used).
4. [x] Remove phenotype with [congenital onsets](https://hpo.jax.org/app/browse/term/HP:0003577), as these are functionally indistinguishable from prenatally onset diseases.
5. [x] Remove filter based on phenotype frequency.
6. [x] Remove filter based on gene frequency.
7. [x] Remove filter based on gene specificity.
8. [x] Set mean expression quantiles filter to include all genes that are expressed, as defined by quantiles >0.
9. [x] Remove phenotype under the "Clinical course" ancestral phenotype as they are too broad.
10. [x] Filter phenotypes based their associations with ["Age of death" terms](https://hpo.jax.org/app/browse/term/HP:0011420). Will need to gather these manually from the HPO site as this info does not appear as a modifier within the [HPO annotations file](https://hpo.jax.org/app/data/annotations).
11. [x] Evaluate how many phenotypes are left when including only Tier 1 vs Tier 1+2.

**Comment by bschilder** [comment]
I've now implemented a new function to annotate phenotypes with their associated Age of Death, which are inferred by their assoication with a given disease: `HPOExplorer::add_death`

Across the whole HPO, here are the number of phenotypes now associated with each Age of Death
```R
table(hpo_death$AgeOfDeath_name)
```
![Screenshot 2023-02-27 at 17 29 44](https://user-images.githubusercontent.com/34280215/221638864-91da493e-3ac3-4285-909c-434ca009a011.png)

Shown here as a percentage of the total HPO terms:
![Screenshot 2023-02-27 at 17 31 37](https://user-images.githubusercontent.com/34280215/221639517-6a6b160b-f84b-42d1-aae8-4e04d2d15407.png)

Within the `MultiEWCE::prioritise_targets` function, I am excluding phenotype belonging to the following age of death categories: "Miscarriage", "Stillbirth", "Prenatal death", NA (no annotation available)

**Comment by bschilder** [comment]
With all the modifications I've made to the filters (see checklist above), this is the breakdown of the filtering steps:
![plot_zoom_png?width=1344 height=844](https://user-images.githubusercontent.com/34280215/221642675-4bdde354-10da-4946-a363-db6620e38e8f.png)


You can see `keep_onsets` results in a big drop in the number of phenotypes now that I'm not including phenotypes with NA for the onset.
`keep_deaths` drops the number of phenotypes further.
After the `keep_tier` step (which now only keeps Tier 1 phenotypes), only 2 phenotypes remain. If I keep both Tier 1+2 phenotypes, 32 phenotypes remain.
By the end of the filtering pipeline, only 2 phenotypes remain: "Intellectual disability"  and  "Global developmental delay"
 
So it would seem that our biggest limiting factor is our ability to assign phenotype to Tiers at the moment.
Potential solutions:
- Use the severity annotations already included in HPO instead of the Lazarin et al criterion.
- Ask the HPO to produce new annotations according to the Lazarin et al criterion.

@NathanSkene given this, how do you think we should proceed?

**Comment by bschilder** [comment]
> Use the severity annotations already included in HPO instead of the Lazarin et al criterion.

Following this line of thought, I tried using mean HPO severity <=1. This didn't do much better than using Tier, as only 6 phenotypes remained (which is too few in my opinion). 

```R
res <- prioritise_targets(keep_tiers = NULL, severity_threshold = 1)
```

These remaining 6 phenotypes also tend to be higher-order HPO terms, which is not ideal:
![Screenshot 2023-02-27 at 18 12 44](https://user-images.githubusercontent.com/34280215/221648220-ab7ad87c-c2fe-47aa-aa8a-f4f5804724b2.png)

**Comment by NathanSkene** [comment]
What’s the range of severity scores? Is it 1-4? What percentage have severity scores?

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by bschilder** [comment]
> What’s the range of severity scores? Is it 1-4? What percentage have severity scores? 

Yes, 1-4 (I think this is coincidentally the same range as Lazarin et al's Tiers).

![Screenshot 2023-02-27 at 18 19 36](https://user-images.githubusercontent.com/34280215/221650551-2ab38bf2-1e1f-467e-9529-8c1b53fa238c.png)


<5% of HPO terms in our enrichment results (before any filtering) have severity scores. So very few.
![Screenshot 2023-02-27 at 18 21 45](https://user-images.githubusercontent.com/34280215/221650452-5b0bbc09-7cf5-4437-af86-4a3bbdb32063.png)

**Comment by NathanSkene** [comment]
Could you send a table with phenotype name and severity score for all those with scores?

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by bschilder** [comment]
> Could you send a table with phenotype name and severity score for all those with scores? 

Attached here

[hpo_modifiers.csv](https://github.com/neurogenomics/RareDiseasePrioritisation/files/10842887/hpo_modifiers.csv)
