### ISSUE TITLE
Generate report on the number of HPO disease modifiers

### ISSUE THREAD

**Issue by bschilder** [neurogenomics/RareDiseasePrioritisation#20]
- [x] Severity modifier
- [x] Lazarin Tiers (manual annotations from Momoko)
- [x] Lazarin Tiers (auto)
- [x] age of onset
- [x] age of death
- [x] phenotype frequency
- [x] Evidence
- [x] Aspect
- [x] Reference
- [x] Biocuration
- [x] Qualifier
- [x] Sex
- [x] disease database source
- [x] additional modifiers

**Comment by bschilder** [comment]
Full report here:

https://neurogenomics.github.io/RareDiseasePrioritisation/reports/HPO_annotations

**Comment by bschilder** [comment]
@NathanSkene requested the following:
>  phenotypes with 20+ diseases’s with associated meta-data

**Comment by NathanSkene** [comment]
What I meant was a bit more detailed than that. Meant what we discussed on the call the other day:

Can we say, that this phenotype, when it acts via this celltype, has a different clinical course?
- To answer this, we want to have at least one phenotype, that has 20 diseases associated with it, where they have at least two different clinical course values (each with >10 diseases)

**Comment by bschilder** [comment]
Made a new issue for this here: #23
