### ISSUE TITLE
Assess whether cell types predict clinical course

### ISSUE THREAD

**Issue by bschilder** [neurogenomics/RareDiseasePrioritisation#23]
Following up from here:
https://github.com/neurogenomics/RareDiseasePrioritisation/issues/20#issuecomment-1481631792

> What I meant was a bit more detailed than that. Meant what we discussed on the call the other day:
> 
> Can we say, that this phenotype, when it acts via this celltype, has a different clinical course?
> 
> * To answer this, we want to have at least one phenotype, that has 20 diseases associated with it, where they have at least two different clinical course values (each with >10 diseases)

**Comment by NathanSkene** [comment]
Can you confirm how many phenotypes have the required data before proceeding with linear modelling? Not clear that we’d be able to use the EWCE pvalue as most the diseases will be single gene

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by bschilder** [comment]
already done, just about to summarise

**Comment by bschilder** [comment]
New report here:
https://neurogenomics.github.io/RareDiseasePrioritisation/reports/differential_outcomes

**Comment by bschilder** [comment]
> Can you confirm how many phenotypes have the required data before proceeding with linear modelling? Not clear that we’d be able to use the EWCE pvalue as most the diseases will be single gene 

Not really sure what you mean by this. This is not a gene-level test. Are you thinking of the other thread? #18 

But here is the answer to the numbers question:
- In our EWCE results data, there were 6170 phenotypes 
- phenotypes were associated with 1- 4403 diseases each (mean=92). 
- 3228 phenotypes remained after filtering to those with >20 diseases
- within this filtered group, phenotypes were associated with 1034 diseases on average
- linear models were run for each phenotypes, using a separate model for each clinical course variable. only tests with sufficient data for that variable in that phenotype were run. 
- in the end, 1043 phenotypes could be run with the metadata we currently have from the HPO annotations (despite being as incomplete as they are). 
- 3129 of the models were signficant at a nominal pvalue<0.05. This encompassed 802 unique phenotypes.

The summary is that it seems to have worked, all clinical outcomes were significantly modified by cell type identity in the vast majority of phenotype tests. See the Rmarkdown report above for details

**Comment by bschilder** [comment]
This summarises the findings visually, and you can see the distribution of clinical courses shifting as you look at test results with an increasingly stringent pvalue threshold.

We're able to visualise the metadata this way because I codified all values for each variable to ordinal scales (eg age of onset, on a score from 1-11).
https://neurogenomics.github.io/HPOExplorer/reference/add_onset.html


![plt](https://user-images.githubusercontent.com/34280215/227497146-35c2dbd1-2b51-44b1-9fb2-152c594df8eb.png)

**Comment by bschilder** [comment]
Realised it didn't quite make sense to use the phenotype-level p-values as this does not vary across diseases (within a phenotype). I think this might be what @NathanSkene was trying to say in our last meeting, but my brain was a bit fried at the time so it didn't sink in.  In those set of analyses, I believe the reason we were seeing significant clinical outcome modifying cell types was an artifact of how i had merge the pre-filtered symptom-level celltype enrichment results.


That said, I've gone back and redone the analyses using the **symptom**-level celltype enrichment p-values, and we actually see far more significant results in which celltype was a significant modifier of clinical outcomes (across all clinical variables).

Here are the top most significant results for each clinical variable. In these plots, the numerically-encoded clinical variable is plotted on the y-axis, and the celltypes that each disease are significantly enriched for (within a phenotype) are on the x-axis. 

![top_modifiying_celltypes](https://user-images.githubusercontent.com/34280215/229091756-26a123b0-d43f-4c6d-b177-3d3fc9282a30.png)


These can be interpreted as examples of phenotypes where the clinical outcomes are variable, and are dependent on which disease (and thus celltype-specific mechanism) is actually causing them. The exact disease is not always known, and typically clinicians have to try and figure this out based on the presence of other phenotypes, medical history, or biomarkers.

A really interesting example is "neonatal hypotonia", which can be an indicator of totally benign conditions all the way through severe ones with high mortality rates.

![Screenshot 2023-03-31 at 11 11 21](https://user-images.githubusercontent.com/34280215/229093171-0bc34a8a-f402-4628-a9ba-c328c1bcf1eb.png)

**Comment by bschilder** [comment]
Next up: 
- [ ] Fix the Descartes CTD (https://github.com/neurogenomics/MultiEWCE/issues/14). If this version of the CTD was indeed used by @bobGSmith , I will also need to rerun all of the original celltype-phenotype enrichment analyses.
- [ ] Rerun the celltype-symptom enrichment analyses using EWCE instead of the simple Fisher's exact tests
- [ ] Rerun the differential clinical outcomes analysis described above.

**Comment by bschilder** [comment]
Now automated as follows:
```R
results <- MSTExplorer::load_example_results()
results <- HPOExplorer::add_death(results,
                                  allow.cartesian = TRUE,
                                  agg_by = c("disease_id","hpo_id"))

## Count number of diseases associated with these phenotypes
keep_descendants <- "Hypotonia" # HP:0001252
hypotonia_results <- HPOExplorer::filter_descendants(results, 
                                                     keep_descendants = keep_descendants) 
hypotonia_results <- MSTExplorer::map_celltype(hypotonia_results)
phenotypes_ids <- unique(hypotonia_results$hpo_id) 
message(length(phenotypes_ids)," unique phenotypes are descendants of ",
        paste(keep_descendants,collapse = "; "))
message(length(unique(hypotonia_results$disease_id) ),
        " unique diseases are associated with: ",
        paste(keep_descendants,collapse = "; "))
message(length(unique(hypotonia_results[q<0.05]$cl_name) ),
        " unique cell types are associated with: ",
        paste(keep_descendants,collapse = "; "))

## Generate plot
differential_outcomes <- MSTExplorer::plot_differential_outcomes_heatmap( 
  results = hypotonia_results, 
  print_phenotypes = TRUE,
  fill_limits = c(1,8),
  save_path = here::here("figures/figure6.pdf"),
  height=8, 
  width=12
)
differential_outcomes$plot
```


![Image](https://github.com/neurogenomics/RareDiseasePrioritisation/assets/34280215/cb976a66-b842-4a7c-8360-fa2bcd59dd3e)
