### ISSUE TITLE
Read about OMIM and HPO... understand the data that's in there... how does it get there? Can it be used to infer prevalence in any way?

### ISSUE THREAD

**Issue by NathanSkene** [neurogenomics/RareDiseasePrioritisation#7]

**Comment by bschilder** [comment]
# HPO papers
2008: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2668030/
2018: https://academic.oup.com/nar/article/47/D1/D1018/5198478
2021: https://academic.oup.com/nar/article/49/D1/D1207/6017351

# HPO sources

HPO merged gene annotations from multiple sources, and maps the terms to the HPO using a combination of NLP and manual curation.

## [OMIM](https://www.omim.org/about)
> For most genes, only selected mutations are included. Criteria for inclusion include the first mutation to be discovered, high population frequency, distinctive phenotype, historic significance, unusual mechanism of mutation, unusual pathogenetic mechanism, and distinctive inheritance (e.g., dominant with some mutations, recessive with other mutations in the same gene).

## [Orphanet](https://www.orpha.net/orphacom/cahiers/docs/GB/Orphanet_Genes_inventory_R1_Ann_gen_EP_02.pdf)

Manually curated disease-gene relationships reported in the literature.
> Each clinical entity within the Orphanet nomenclature of RDs is enriched by scientific and textual information. 

## [DECIPHER](https://www.deciphergenomics.org/about/faqs)

```
DECIPHER accepts the following variant data with associated phenotypes:
Sequence variants
Copy number variants
Aneuploidy/Segmental aneuploidy
Uniparental Disomy
Inversions
Mobile Elements (Alu, LINE1, SVA)
Retrogenes
Other insertions
```


HPO FAQ: "What is your procedure for associating genes with HPO phenotypes?"
https://hpo.jax.org/app/faq
>In many cases, there are multiple diseases that are associated with mutations in the same gene (for instance, mutations in the LMNA gene are associated with multiple diseases including Cardiomyopathy, dilated, 1A [MIM:115200], Charcot-Marie-Tooth disease, type 2B1 [605588], Emery-Dreifuss muscular dystrophy 2, AD [181350], and Hutchinson-Gilford progeria [176670]. Each of these diseases is associated with a different spectrum of phenotypic features. The gene-to-phenotype association in our databases takes the set of all phenotypic features (HPO terms) associated with one or more diseases caused by mutation in the gene under consideration. Thus, LMNA is associated with Alopecia (which is a feature of Hutchinson-Gilford progeria) as well as Ventricular arrhythmia (which is a feature of Cardiomyopathy, dilated, 1A).
